import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import HeaderNavBar from "../components/HeaderNavBar";
import { Providers } from "./Provider";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <body>
          <Providers>
            <HeaderNavBar />
            {children}
          </Providers>
        </body>
      </body>
    </html>
  );
}
